plot(dBm0.VarName1,dBm0.VarName2);
hold on;
plot(dBm1.VarName1,dBm1.VarName2);
hold on;
plot(dBm2.VarName1,dBm2.VarName2);
hold on;
plot(dBm3.VarName1,dBm3.VarName2);
hold on;
plot(dBm6.VarName1,dBm6.VarName2);
hold on;
