plot(dBm0.VarName1,dBm0.VarName2);
hold on;
plot(dBm1.VarName1,dBm1.VarName2);
hold on;
plot(dBm2.VarName1,dBm2.VarName2);
hold on;
plot(dBm3.VarName1,dBm3.VarName2);
hold on;
plot(dBm4.VarName1,dBm4.VarName2);
hold on;
plot(dBm5.VarName1,dBm5.VarName2);
hold on;
plot(dBm6.VarName1,dBm6.VarName2);
hold on;
plot(dBm7.VarName1,dBm7.VarName2);
hold on;
plot(dBm8.VarName1,dBm8.VarName2);
hold on;
plot(dBm9.VarName1,dBm9.VarName2);
hold on;
plot(dBm_1.VarName1,dBm_1.VarName2);
hold on;
plot(dBm_2.VarName1,dBm_2.VarName2);
hold on;
plot(dBm_3.VarName1,dBm_3.VarName2);
hold on;
plot(dBm_4.VarName1,dBm_4.VarName2);
hold on;
plot(dBm_5.VarName1,dBm_5.VarName2);
hold on;
plot(dBm_6.VarName1,dBm_6.VarName2);
hold on;
plot(dBm_7.VarName1,dBm_7.VarName2);
hold on;
plot(dBm_8.VarName1,dBm_8.VarName2);
hold on;
plot(dBm_9.VarName1,dBm_9.VarName2);
hold on;
plot(dBm_10.VarName1,dBm_10.VarName2);
hold on;
plot(dBm_11.VarName1,dBm_11.VarName2);
hold on;
plot(dBm_12.VarName1,dBm_12.VarName2);